# Scaffolding generated by Casein v5.3.0.0

module Casein
  class EpisodesController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Episodes'
      @episodes = Episode.order(sort_order(:episode_number)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View episode'
      @episode = Episode.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new episode'
      @episode = Episode.new
    end

    def create
      @episode = Episode.new episode_params

      if @episode.save
        flash[:notice] = 'Episode created'
        redirect_to casein_episodes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new episode'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update episode'

      @episode = Episode.find params[:id]

      if @episode.update_attributes episode_params
        flash[:notice] = 'Episode has been updated'
        redirect_to casein_episodes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this episode'
        render action: :show
      end
    end

    def destroy
      @episode = Episode.find params[:id]

      @episode.destroy
      flash[:notice] = 'Episode has been deleted'
      redirect_to casein_episodes_path
    end

    private

    def episode_params
      params.require(:episode).permit(:episode_number, :title, :description, :url)
    end
  end
end
